#!/bin/bash

cd ~/.vim
ln -s .vim/vimrc .vimrc
git submodule init && git submodule update

# Build Command-T plug-in
sudo apt-get install vim-nox ruby ruby-dev
cd ~/.vim/bundle/command-t/ruby/command-t
ruby extconf.rb
make
